// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbb8GWSx-sVl1kmArrJ80Uxri063_cALM',
    appId: '1:572574179213:web:74eb5fb2bba8a1fc9127c4',
    messagingSenderId: '572574179213',
    projectId: 'dog-tinder-backend',
    authDomain: 'dog-tinder-backend.firebaseapp.com',
    storageBucket: 'dog-tinder-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jm3poHgvrKyjXSkQZwc6BxjeAMSpzIc',
    appId: '1:572574179213:android:993f5b7b53cf0db29127c4',
    messagingSenderId: '572574179213',
    projectId: 'dog-tinder-backend',
    storageBucket: 'dog-tinder-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsGOHOTrMpBCLdGuc_RIFSvgJ-ItgOBrM',
    appId: '1:572574179213:ios:870103b477f6684b9127c4',
    messagingSenderId: '572574179213',
    projectId: 'dog-tinder-backend',
    storageBucket: 'dog-tinder-backend.appspot.com',
    iosClientId: '572574179213-jbv6a0fu9h907nlrg53p1mpus9pb8i1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsGOHOTrMpBCLdGuc_RIFSvgJ-ItgOBrM',
    appId: '1:572574179213:ios:870103b477f6684b9127c4',
    messagingSenderId: '572574179213',
    projectId: 'dog-tinder-backend',
    storageBucket: 'dog-tinder-backend.appspot.com',
    iosClientId: '572574179213-jbv6a0fu9h907nlrg53p1mpus9pb8i1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogTinder',
  );
}
